# Generated by Django 4.0.5 on 2022-08-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DOCUMENTO_IDENTIDAD',
            fields=[
                ('codDocumentoIdentidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('codTrabajador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=100)),
                ('fechaContratos', models.DateField(auto_now_add=True)),
                ('nroDocumento', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('codDocumentoIdentidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trabajadores.documento_identidad')),
            ],
        ),
    ]
