# Generated by Django 4.0.5 on 2022-08-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento_Identidad',
            fields=[
                ('coddocumentoidentidad', models.AutoField(max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codproveedor', models.AutoField(max_length=8, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=50)),
                ('razonsocial', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
                ('nrodocumento', models.CharField(max_length=5)),
                ('coddocumentoidentidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InicioDashboard.documento_identidad')),
            ],
        ),
    ]
