# Generated by Django 4.0.5 on 2022-08-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InicioDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento_identidad',
            name='coddocumentoidentidad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codproveedor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
