# Generated by Django 4.0.5 on 2022-08-08 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InicioDashboard', '0002_alter_documento_identidad_coddocumentoidentidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('idBanco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('nroCuenta', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('tipoCuenta', models.CharField(max_length=20)),
                ('activo', models.BooleanField()),
                ('idBanco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InicioDashboard.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('idMoneda', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='coddocumentoidentidad',
        ),
        migrations.DeleteModel(
            name='Documento_Identidad',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='idMoneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InicioDashboard.moneda'),
        ),
    ]
