# Generated by Django 4.0.5 on 2022-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InicioDashboard', '0003_banco_cuentabancaria_moneda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=8)),
                ('edad', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('nroDocumento', models.CharField(max_length=20)),
                ('codDocumentoIdentidad', models.CharField(max_length=5)),
                ('razonSocial', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Documento_Identidad2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coddocumentoidentidad', models.CharField(max_length=8)),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=50)),
                ('razonsocial', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
                ('nrodocumento', models.CharField(max_length=15)),
                ('coddocumentoidentidad', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='DNI', max_length=3)),
            ],
        ),
    ]
