# Generated by Django 4.0.5 on 2022-08-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='nombre',
            new_name='rol',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=9)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=100)),
                ('celular', models.IntegerField()),
                ('eliminado', models.BooleanField(default=False)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridadApp.rol')),
            ],
        ),
        migrations.CreateModel(
            name='NuevoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=9)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('celular', models.IntegerField()),
                ('eliminado', models.BooleanField(default=False)),
                ('rol', models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to='seguridadApp.rol')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
