# Generated by Django 4.0.5 on 2022-08-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadApp', '0004_alter_nuevousuario_correo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NuevoUsuario',
        ),
    ]
